# Site settings
title: xiaOp的博客
email: pyqiverson@gmail.com
description: >
  读书笔记，碰到的问题
keywords:
  - coding
  - 编程
  - javascript
  - xiaoiver
  - xiaop
chrome-tab-theme-color: "#eee"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://xiaoiver.github.io" # the base hostname & protocol for your site
github_username: xiaoiver

highlighter: rouge

# Build settings
markdown: kramdown

# Pagination
paginate: 5

# Gems plugins
# plugins: [jekyll-paginate, jekyll-seo-tag]
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-responsive-image

# Responsive image
responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 480
      quality: 80
    - width: 800
    - width: 1400
      quality: 90
  output_path_format: img/resized/%{width}/%{basename}
